### PR TITLE
Adopt new endpoint: https://api.gandi.net/v5/

### PR DESCRIPTION
**Pull request by TomOnTime**
As recommended by @baloo, use the newer endpoint.

FYI: I wasn't able to test a lot of these changes. My code that uses this module all works. However I use /domains not /zones. I point this out because /zones doesn't appear in the new docs.

### CODE REVIEW

**Comment by tiramiseb** [comment]
Thanks for this PR !

@baloo, regarding the fact that /zones don't appear in the new docs, do you have some insight? Is it abandoned? Should I remove it from this lib?

Thanks!

**Comment by baloo** [comment]
That is a very good point, please do not merge right now as what is not exposed in the documentation is filtered by the proxy! So this will break the current implementation.

I'll ask the question internally and I will update you asap (sadly it's holiday season, that might take a week or two for me to get a grip on the right person :/).

**Comment by tiramiseb** [comment]
No problem, I'll just spend more time with the kids during the holiday :joy:

**Comment by TomOnTime** [comment]
Agreed. I want to share my gratitude to you (both) for looking at this on the weekend, especially a holiday weekend.

Time with family is more important than this!

**Comment by thommay** [comment]
hey @TomOnTime , sorry i hadn't seen this PR before I started working on #8 but since I raised #5 and no-one else had done anything here for a year I didn't think to check :) One of the things i've done in my PR is to break out LiveDNS and Domains into separate packages so it's clear which part of the API you're interacting with. They also return quite different objects so it makes life a bit easier there too. WDYT?

**Comment by TomOnTime** [comment]
That sounds good!

I'd be willing to withdraw my PR. Yours seems to be more advanced.

Though, I'd caution you against too much complexity. This is Go, not Java.  :-)  What attracted me to this module for use in [DNSControl](https://github.com/StackExchange/dnscontrol) was that it was easy to get started with and doesn't try to do too much.

**Comment by tiramiseb** [comment]
Not sure separating into different packages is useful.

Moreover, I have created this library for the Terraform Gandi provider (https://github.com/tiramiseb/terraform-provider-gandi), having multiple packages would make that provider more complex too.

**Comment by olivier-m** [comment]
Hi! When writing the new public API, we decided not to expose the zone endpoint. It appears to be quite complex and seemed to be not so useful. Of course, I'd be happy to change my mind about this :)
So I can understand the context, do you have any use case where having the zone api would make your life much easier?

**Comment by tiramiseb** [comment]
Honestly, I have simply implemented everything needed to execute the example on https://doc.livedns.gandi.net/. In that documentation, IIRC, directly manipulating a domain's entry is not possible, and you need to attach a domain to a zone.
Indeed, exposing the zone endpoint is possibly useless, as long as you can manipulate a domain...

However, I have already used a zone file for multiple domaines, for instance when I had a ".fr" domain and a ".com" domain, both with exactly the same servers... A change on the zone resulted on a change on both domains, it was simpler. But well, creating two entries would not have been too complex :)

**Pull request closed without merging**
